name: kashly
description: Professional cashbook and transaction management app with advanced backup, sync, and audit controls.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.7
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  workmanager: ^0.6.0 
  uuid: ^4.4.2
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  shared_preferences: ^2.3.0
  file_picker: ^8.1.2
  fl_chart: ^0.70.0
  csv: ^5.1.0
  pdf: ^3.10.8
  crypto: ^3.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_local_notifications: ^17.2.2
  local_auth: ^2.3.0
  open_file: ^3.3.2
  share_plus: ^10.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  battery_plus: ^6.0.3
  logger: ^2.4.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
