name: 2. Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.0'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/kashly-release.keystore

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=kashly-release.keystore" >> android/key.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze
         
      - name: Build APK
        run: flutter build apk --release

      - name: Extract SHA fingerprints
        run: |
          keytool -list -v \
            -keystore android/app/kashly-release.keystore \
            -alias "${{ secrets.KEYSTORE_ALIAS }}" \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" > fingerprint.txt

          SHA1=$(grep "SHA1:" fingerprint.txt | head -n1 | sed 's/.*SHA1: //')
          SHA256=$(grep "SHA256:" fingerprint.txt | head -n1 | sed 's/.*SHA256: //')

          echo "## ðŸ” Signing Certificate Fingerprints" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**SHA-1**  \`$SHA1\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**SHA-256**  \`$SHA256\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kashly_V_
          path: build/app/outputs/flutter-apk/app-release.apk
