name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore kashly-release.keystore \
            -alias Kashly \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass 284619 \
            -keypass 284619 \
            -dname "CN=Kashly, OU=Dev, O=Kashly, L=Jodhpur, ST=Rajasthan, C=IN"

      - name: Convert to Base64
        run: base64 kashly-release.keystore > keystore.txt

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: kashly-keystore
          path: |
            kashly-release.keystore
            keystore.txt
